<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="MAIN" Id="{97acbdd3-2ab4-4801-ab26-b5f1255e7431}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR 
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[Accuracy_Measurement();]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="6" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>