<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="PRG_Vision" Id="{150307bd-cc4d-4297-ba9b-9aa1f2cc8252}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM PRG_Vision
]]></Declaration>
    <Implementation>
      <ST><![CDATA[fbMachine.UpdateSlow();]]></ST>
    </Implementation>
    <LineIds Name="PRG_Vision">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>