<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Productversion="">
  <POU Name="F_DCTimestructToFileTime" Id="cc39a967-6f0b-4a82-923d-37599a3ad30a" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION F_DCTimestructToFileTime : ULINT
VAR_INPUT
	dtTimestamp: DCTIMESTRUCT;
END_VAR
VAR
	dcTime: T_DCTIME64;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[dcTime:= DCTIMESTRUCT_TO_DCTIME64(dtTimestamp);
F_DCTimestructToFileTime:= F_AlyTimestampToFileTime(dcTime);]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>